#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom stats lm.fit
#' @importFrom stats lm.wfit
#' @importFrom stats model.frame
#' @importFrom stats model.matrix
#' @importFrom stats model.response
#' @importFrom stats delete.response
#' @importFrom stats quantile
#' @importFrom stats median
#' @importFrom stats var
#' @importFrom stats sd
#' @importFrom stats coef
#' @importFrom stats fitted
#' @importFrom stats residuals
#' @importFrom stats predict
#' @importFrom stats qnorm
#' @importFrom stats pnorm
#' @importFrom stats qchisq
#' @importFrom stats ppoints
#' @importFrom stats density
#' @importFrom stats approx
#' @importFrom stats cor
#' @importFrom stats cov
#' @importFrom stats complete.cases
#' @importFrom stats na.fail
#' @importFrom stats .getXlevels
#' @importFrom stats setNames
#' @importFrom graphics plot
#' @importFrom graphics par
#' @importFrom graphics lines
#' @importFrom graphics points
#' @importFrom graphics legend
#' @importFrom graphics abline
#' @importFrom graphics hist
#' @importFrom graphics mtext
#' @importFrom graphics polygon
#' @importFrom graphics text
#' @importFrom graphics segments
#' @importFrom stats crossprod
#' @importFrom stats vcov
#' @importFrom MASS ginv
#' @importFrom sm h.select
#' @importFrom graphics box
#' @importFrom grDevices rgb
## usethis namespace: end
NULL
